### PR TITLE
Chore/update everything

### PR DESCRIPTION
**Pull request by Haroenv**
Nuxt and multi-index have really weird errors

### CODE REVIEW

**Comment by Haroenv** [comment]
No idea why it’s broken though :(

**Comment by rayrutjes** [comment]
It doesn't break on master, so it must be related to all the upgrades.

**Comment by rayrutjes** [comment]
Feel free to take decisions though. Not sure what would be a better way to have a more maintainable examples repo.

**Comment by vvo** [comment]
Upgrading everything at once is hard but feasible. Let's ensure we setup renovate afterwards

**Comment by vvo** [comment]
There should be a single yarn.lock at the root, a travis.yml file maybe, nvmrc, renovate.json, eslint ..

let me know what you think

**Comment by Haroenv** [comment]
@vvo, that was exactly my plan, but stuck at this PR because I wasn't sure what caused the two regressions, and still trying to figure out how to get them back in a working state :)

**Comment by vvo** [comment]
> and still trying to figure out how to get them back in a working state :)

Update one dep after the other and see when it breaks (I am sure that's what you are already doing, but stil)

**Pull request merged**
